---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lb-notifications-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/lb-conn/lb-notifications-config
    targetRevision: main
    path: environments/prd
  destination:
    server: https://8FD0228363C30A78286C184D69B58244.yl4.sa-east-1.eks.amazonaws.com
    namespace: lb-notifications
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
