---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lb-notifications-shared-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: lb-notifications-shared-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /lb-notifications/dev/manual-secrets

