---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lb-notifications-shared-secret
  labels:
    app.kubernetes.io/part-of: lb-notifications
    argocd.argoproj.io/instance: lb-notifications-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: lb-notifications-shared-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: PULSAR_API_KEY
      remoteRef:
        key: /lb-notifications/dev/manual-secrets
        property: PULSAR_API_KEY
    - secretKey: NOVU_API_KEY
      remoteRef:
        key: /lb-notifications/dev/manual-secrets
        property: NOVU_API_KEY
    - secretKey: NOVU_API_URL
      remoteRef:
        key: /lb-notifications/dev/manual-secrets
        property: NOVU_API_URL
